### ISSUE TITLE
Markers are not touch/clickable on mobile devices

### ISSUE THREAD

**Issue by magnolo** [magnolo/newhere#113]
There is no response when trying to touch the map markers on mobile devices. So the touchend event doesnt seem to fire

**Comment by connyduck** [comment]
This is a Heisenbug. As soon as I attach a debugger to my mobile device or run the site in a mobile emulator, it works. 
I already tried the solution proposed here, but it seems to do nothing: https://github.com/tombatossals/angular-leaflet-directive/issues/743#issuecomment-103917857

**Comment by magnolo** [comment]
yeah. i have seen that. i also published the event-broadcast attribute on leaflet directive. with no luck.

**Comment by johnedvard** [comment]
I have the same issue. It seems that when I register a `click`-event it does not fire. The `doubleclick`-event however, is triggered.

**Comment by kardanov** [comment]
hey guys,
just as a hint (in case you didn't solve it yet): 
could it be not angular-leaflet-directive who stealing your taps/clicks?
i had similar problem and finally found out that it was angular-material hijacking my taps/clicks on mobile devices. possible solution described here:
http://stackoverflow.com/questions/38618541/tap-click-marker-events-not-working-in-angular-leaflet-directive-on-mobile-devic

**Comment by johnedvard** [comment]
I just figured out that it was angular-material who was hijacking the click-events
